[tool.poetry]
name = "python-project-50"
version = "0.1.0"
description = ""
authors = ["Yakovishin Timofey"]
readme = "README.md"
packages = [{include = "python_project_50"}]

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
